# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b3da32083508063d7b9b7e3a1d039b9"
application_url = "https://tool-required-salary-exceptional.trycloudflare.com"
embedded = true
name = "web-app"
handle = "web-app-23"

[build]
include_config_on_deploy = true
dev_store_url = "vivek-test-store-amirait.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tool-required-salary-exceptional.trycloudflare.com/auth/callback",
  "https://tool-required-salary-exceptional.trycloudflare.com/auth/shopify/callback",
  "https://tool-required-salary-exceptional.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
